[package]
name = "sif-encoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorsys = "0.6.5"
image = "0.23.14"
gflags = "0.3.9"
serde_json = "1.0.72"
